# Generated by Django 3.2.9 on 2022-01-06 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_pay', models.IntegerField(default=0)),
                ('payment_status', models.CharField(default='Unpaid', max_length=50)),
                ('last_payment', models.DateField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount_to_pay', models.IntegerField(default=10000)),
                ('paid', models.IntegerField(default=0)),
                ('status', models.CharField(default='Unpaid', max_length=50)),
                ('semester_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesterSystem.semestersystem')),
            ],
        ),
    ]
