# Generated by Django 3.2.9 on 2022-01-06 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('semesterSystem', '0005_alter_semestersystem_last_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersystem',
            name='last_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 19, 19, 41, 454053, tzinfo=utc), verbose_name='Last payment'),
        ),
    ]
