# Generated by Django 3.2.9 on 2022-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterSystem', '0006_alter_semestersystem_last_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersystem',
            name='last_payment',
            field=models.DateTimeField(auto_now=True, verbose_name='Last payment'),
        ),
    ]
