# Generated by Django 3.2.9 on 2022-01-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesterSystem', '0007_alter_semestersystem_last_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestersystem',
            name='last_payment',
        ),
    ]
