# Generated by Django 3.2.9 on 2022-01-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterSystem', '0009_midtermfee_registrationfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermfee',
            name='status',
            field=models.CharField(default='Unpaid', max_length=50),
        ),
        migrations.AddField(
            model_name='registrationfee',
            name='status',
            field=models.CharField(default='Unpaid', max_length=50),
        ),
    ]
