# Generated by Django 3.2.9 on 2022-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterSystem', '0013_auto_20220415_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersystem',
            name='department',
            field=models.CharField(default='Computer Science and Technology(85)', max_length=300),
        ),
        migrations.AddField(
            model_name='semestersystem',
            name='session',
            field=models.CharField(default='2019-2020', max_length=50),
        ),
    ]
