# Generated by Django 3.2.9 on 2022-02-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Father name'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mother name'),
        ),
        migrations.AddField(
            model_name='user',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Session'),
        ),
    ]
