# Generated by Django 3.2.9 on 2022-02-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220204_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father_is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
