# Generated by Django 3.2.9 on 2022-02-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_father_is_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='special_discount',
            field=models.BooleanField(default=False),
        ),
    ]
