# Generated by Django 3.2.9 on 2022-02-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220205_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deafen',
            field=models.BooleanField(default=False),
        ),
    ]
