# Generated by Django 3.2.9 on 2022-02-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Computer Science and Technology(85)', 'Computer Science and Technology(85)'), ('Computer Technology(66)', 'Computer Technology(66)'), ('Architecture and Interior Design Technology(87)', 'Architecture and Interior Design Technology(87)'), ('Civil Technology(64)', 'Civil Technology(64)'), ('Electrical  Technology(67)', 'Electrical  Technology(67)')], max_length=100, null=True, verbose_name='Department'),
        ),
    ]
