# Generated by Django 3.2.9 on 2022-01-04 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='class_routine_files')),
                ('semester', models.IntegerField(choices=[(1, '1st semester'), (2, '2nd semester'), (3, '3rd semester'), (4, '4th semester'), (5, '5th semester'), (6, '6th semester'), (7, '7th semester')])),
                ('department', models.CharField(choices=[('computer_science_technology', 'Computer Science Technology'), ('civil_technology', 'Civil Technology'), ('architecture_technology', 'Architecture Technology'), ('textile_technology', 'TextTile Technology'), ('electrical_engineering', 'Electrical Engineering')], max_length=100)),
                ('year', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='routine_files')),
                ('semester', models.IntegerField(choices=[(1, '1st semester'), (2, '2nd semester'), (3, '3rd semester'), (4, '4th semester'), (5, '5th semester'), (6, '6th semester'), (7, '7th semester')])),
                ('year', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.CharField(choices=[('computer_science_technology', 'Computer Science Technology'), ('civil_technology', 'Civil Technology'), ('architecture_technology', 'Architecture Technology'), ('textile_technology', 'TextTile Technology'), ('electrical_engineering', 'Electrical Engineering')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('registration', models.BigIntegerField()),
                ('semester', models.CharField(choices=[(1, '1st semester'), (2, '2nd semester'), (3, '3rd semester')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='results')),
                ('session_year', models.DateTimeField(auto_now_add=True)),
                ('which_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeSystem.semester')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.BigIntegerField()),
                ('registration', models.BigIntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='grade_sheets')),
                ('up_result_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeSystem.uploadresult')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=6)),
                ('subject_code', models.CharField(max_length=8)),
                ('mark', models.CharField(max_length=4)),
                ('grade_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeSystem.gradefile')),
            ],
        ),
    ]
