# Generated by Django 3.2.9 on 2022-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.IntegerField()),
                ('subject_name', models.CharField(max_length=50)),
                ('total_mark', models.IntegerField()),
            ],
        ),
    ]
