# Generated by Django 3.2.9 on 2022-01-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0003_testsubchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testsubchoice',
            name='sub',
            field=models.CharField(choices=[['Business Organization and Communications (65842)', 'Business Organization and Communications (65842)'], ['Data Structure and Algorithms (65441)', 'Data Structure and Algorithms (65441)'], ['Object Oriented Programming (65443)', 'Object Oriented Programming (65443)']], max_length=5000),
        ),
    ]
