# Generated by Django 3.2.9 on 2022-01-24 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collegeSystem', '0005_auto_20220124_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.BigIntegerField()),
                ('registration', models.BigIntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('mark', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeSystem.result')),
            ],
        ),
        migrations.DeleteModel(
            name='ResultSheet',
        ),
    ]
