# Generated by Django 3.2.9 on 2022-01-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0006_auto_20220124_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='status',
            new_name='grade_char',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='grade',
            new_name='grade_point',
        ),
    ]
