# Generated by Django 3.2.9 on 2022-01-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0007_auto_20220125_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storegrade',
            old_name='grade',
            new_name='grade_chr',
        ),
        migrations.AddField(
            model_name='storegrade',
            name='grade_point',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='grade_point',
            field=models.FloatField(),
        ),
    ]
