# Generated by Django 3.2.9 on 2022-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0009_auto_20220125_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadresult',
            name='which_semester',
            field=models.IntegerField(choices=[(1, '1st semester'), (2, '2nd semester'), (3, '3rd semester'), (4, '4th semester'), (5, '5th semester'), (6, '6th semester'), (7, '7th semester')]),
        ),
    ]
