# Generated by Django 3.2.9 on 2022-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0012_auto_20220204_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadresult',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadresult',
            name='exam',
            field=models.CharField(choices=[('FIRST SEMESTER EXAMINATION', 'FIRST SEMESTER EXAMINATION'), ('SECOND SEMESTER EXAMINATION', 'SECOND SEMESTER EXAMINATION'), ('THIRD SEMESTER EXAMINATION', 'THIRD SEMESTER EXAMINATION')], default='None', max_length=150),
            preserve_default=False,
        ),
    ]
