# Generated by Django 3.2.9 on 2022-02-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0013_auto_20220204_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='collegeSystem.uploadresult'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadresult',
            name='which_semester',
            field=models.IntegerField(choices=[(1, '1st semester'), (2, '2nd semester'), (3, '3rd semester')]),
        ),
    ]
