# Generated by Django 3.2.9 on 2022-02-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0015_auto_20220205_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadresult',
            name='exam_year',
            field=models.CharField(max_length=30),
        ),
    ]
