# Generated by Django 3.2.9 on 2022-02-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0017_auto_20220210_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storegrade',
            name='subject_code',
        ),
        migrations.RemoveField(
            model_name='storegrade',
            name='subject_mark',
        ),
        migrations.RemoveField(
            model_name='storegrade',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='storegrade',
            name='s_p_c_asses_obt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storegrade',
            name='s_p_f_exam_obt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storegrade',
            name='s_t_c_asses_obt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storegrade',
            name='s_t_f_exam_obt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storegrade',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='collegeSystem.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='s_p_t_c_asses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='s_p_t_f_exam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='s_t_t_c_asses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='s_t_t_f_exam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='sub_p_c_a_pass_mark',
            field=models.IntegerField(blank=True, default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='sub_p_f_e_pass_mark',
            field=models.IntegerField(blank=True, default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='sub_t_c_a_pass_mark',
            field=models.IntegerField(blank=True, default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='sub_t_f_e_pass_mark',
            field=models.IntegerField(blank=True, default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='department',
            field=models.CharField(choices=[('Computer Science and Technology(85)', 'Computer Science and Technology(85)'), ('Computer Technology(66)', 'Computer Technology(66)'), ('Architecture and Interior Design Technology(87)', 'Architecture and Interior Design Technology(87)'), ('Civil Technology(64)', 'Civil Technology(64)'), ('Electrical  Technology(67)', 'Electrical  Technology(67)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='department',
            field=models.CharField(choices=[('Computer Science and Technology(85)', 'Computer Science and Technology(85)'), ('Computer Technology(66)', 'Computer Technology(66)'), ('Architecture and Interior Design Technology(87)', 'Architecture and Interior Design Technology(87)'), ('Civil Technology(64)', 'Civil Technology(64)'), ('Electrical  Technology(67)', 'Electrical  Technology(67)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadresult',
            name='department',
            field=models.CharField(choices=[('Computer Science and Technology(85)', 'Computer Science and Technology(85)'), ('Computer Technology(66)', 'Computer Technology(66)'), ('Architecture and Interior Design Technology(87)', 'Architecture and Interior Design Technology(87)'), ('Civil Technology(64)', 'Civil Technology(64)'), ('Electrical  Technology(67)', 'Electrical  Technology(67)')], max_length=100),
        ),
    ]
