# Generated by Django 3.2.9 on 2022-02-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0018_auto_20220218_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='total_mark_to_pass',
            field=models.IntegerField(default=0),
        ),
    ]
