# Generated by Django 3.2.9 on 2022-02-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0019_subjects_total_mark_to_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storegrade',
            name='grade_point',
            field=models.CharField(default='0.00', max_length=4),
        ),
    ]
