# Generated by Django 3.2.9 on 2022-02-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0020_alter_storegrade_grade_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadresult',
            name='session',
            field=models.CharField(default='2020-2021', max_length=30),
            preserve_default=False,
        ),
    ]
