# Generated by Django 3.2.9 on 2022-02-21 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0021_uploadresult_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroutine',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
