# Generated by Django 3.2.9 on 2022-04-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeSystem', '0022_examroutine_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
    ]
