# Generated by Django 3.2.9 on 2022-01-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='last_payment',
            field=models.DateField(auto_now=True),
        ),
    ]
