# Generated by Django 3.2.9 on 2022-01-26 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reason', models.CharField(max_length=200)),
                ('transaction_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('student_roll', models.BigIntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('signature_of_student', models.CharField(max_length=50)),
                ('signature_of_accountant', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField(default=0)),
                ('recipient_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
