# Generated by Django 3.2.9 on 2022-01-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_id',
            field=models.CharField(max_length=36),
        ),
    ]
