# Generated by Django 3.2.9 on 2022-01-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220127_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='group',
            new_name='department',
        ),
    ]
