# Generated by Django 3.2.9 on 2022-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_group_transaction_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
    ]
