# Generated by Django 3.2.9 on 2022-01-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_transactionreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='transaction',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dashboard.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_reason',
            field=models.CharField(choices=[['Admission Fee', 'Admission Fee'], ['Admission Form', 'Admission Form'], ['Tution Fee', 'Tution Fee'], ['Advance', 'Advance'], ['Registration Fee', 'Registration Fee'], ['Session Fee', 'Session Fee'], ['Semester Fee', 'Semester Fee'], ['Mid Semester Fee', 'Mid Semester Fee'], ['Hostel Fee', 'Hostel Fee'], ['Hostel Fee', 'Hostel Fee'], ['Form Fill Up Fee', 'Form Fill Up Fee'], ['Rover Scouts', 'Rover Scouts'], ['Magazine', 'Magazine'], ['Library', 'Library'], ['Industrial Attachment Fee', 'Industrial Attachment Fee'], ['Equipment of practical Class', 'Equipment of practical Class'], ['Affiliation Fee', 'Affiliation Fee'], ['Medical', 'Medical'], ['Fine', 'Fine'], ['Others', 'Others'], ['T.C/C.C.C', 'T.C/C.C.C'], ['Sports', 'Sports']], max_length=200),
        ),
    ]
