# Generated by Django 3.2.9 on 2022-01-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220128_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, default='test@gmail.com', max_length=254, null=True),
        ),
    ]
