# Generated by Django 3.2.9 on 2022-02-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220202_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='custom_receipt_id',
            field=models.IntegerField(default=0),
        ),
    ]
