# Generated by Django 3.2.9 on 2022-04-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_reason',
            field=models.CharField(choices=[], max_length=200),
        ),
    ]
