# Generated by Django 3.2.9 on 2022-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_statementhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_reason',
            field=models.CharField(choices=[['Mid Semester Fee', 'Mid Semester Fee'], ['Form Fill Up Fee', 'Form Fill Up Fee'], ['Semester Fee', 'Semester Fee'], ['Hostel Fee', 'Hostel Fee']], max_length=200),
        ),
    ]
