# Generated by Django 3.2.9 on 2022-04-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_transactiondetails_transaction_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataContainerArrears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('registration', models.BigIntegerField()),
                ('total', models.IntegerField()),
                ('current', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentContainerArrears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubContainerArrears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('total_amount', models.CharField(max_length=100)),
                ('data_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.datacontainerarrears')),
            ],
        ),
        migrations.AddField(
            model_name='datacontainerarrears',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.parentcontainerarrears'),
        ),
    ]
