# Generated by Django 3.2.9 on 2022-04-18 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0016_auto_20220417_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_reason',
            field=models.CharField(choices=[['Mid Semester Fee', 'Mid Semester Fee'], ['Form Fill Up Fee', 'Form Fill Up Fee'], ['Semester Fee', 'Semester Fee'], ['Hostel Fee', 'Hostel Fee'], ['Others', 'Others']], max_length=200),
        ),
        migrations.CreateModel(
            name='TransactionStatementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
